In [ ]:
import numpy as np

In [ ]:
# Array attributes

arr = np.array([[2,4,5,7],[1,3,6,9]])

# Array Shape
shape = arr.shape
dimension = arr.ndim
size = arr.size
print(f'Array shape is: {shape}')
print(f'Array dimension is: {dimension}')
print(f'Array size is: {size}')

# Access array elements
# Remember index begins from zero
element = arr[1][3]
print(element)

In [ ]:
# Creating a Range of array elements
# From zero excluding 30 with intervals of 3
arr_Range = np.arange(0,30,3) 
print(arr_Range)

In [ ]:
# Creating numbers from 0-10 with 20 increaments
# # Creating numbers from 0-10 with 20 increaments
# Returns evenly spaced numbers over specified interval
arr_ls = np.linspace(1,10,20)
print(arr_ls)

In [ ]:
# Generating random numbers
# rand generates random numbers between 0-1
rand = np.random.rand(20)
print(rand)

# Reshape array into a 3 dimensional array
my_array = np.random.rand(4,5)
print(my_array)

# Generating random intergers between a given range
# Start, end, number of intergers
rand_int = np.random.randint(11,23,6)
print(rand_int)

In [ ]:
# Generating array logs
# Sin, Cosin, tan, sum,
arr_lg = np.log(arr_ls)
print(arr_lg)

# Generating Exponent
arr_exp = np.exp(arr_ls)
print(arr_exp)

In [ ]:
# Array axis mean, max, std, var and median
# axis = 1 implies rows and 0 implies columns
sum_Row = np.sum(my_array,axis = 1)
sum_Column = np.sum(my_array,axis = 0)

print(sum_Row)
print(sum_Column)

print('*********Man and Max*********')

mean_Row = np.mean(my_array,axis = 1)
max_Column = np.max(my_array,axis = 0)
max_arr = np.max(my_array)

print(mean_Row)
print(max_Column)
print(max_arr)

In [ ]:
# Slicing arrays

# slice1 = my_array[1] # Prints just array at index 1
# slice1 = my_array[1:] # Prints from index 1 till end
# slice1 = my_array[1:3] # Prints from index 1-3 excluding 3
# slice1 = my_array[1:,3] # Get column 3 from array index 1 till the end
# slice1 = my_array[0:,3:-1] # Get column 3 excluding last column
# slice1 = my_array[0:,2:-1] # Get column 3 excluding last column
slice1 = my_array[0:,-1] # Get last column

print(slice1)

In [ ]:
# Transpose
# Reversis the x axis
arr_t = my_array.T
print(arr_t)

In [ ]:
# Flatenning
# Flatterns into a single array
arr_f = my_array.flatten()
print(arr_f)

In [ ]:
# Array Concartenation

arr_con = np.array([2,4,6,8,9])

# Append
arr_con = np.append(arr_con,43)

# Insert
arr_con = np.insert(arr_con,2,[11,23,67])

arr_con = np.delete(arr_con,[4,8])
# print(arr_con)

# Concart two arrays
arr1 = np.array([[2,4,6,8],[10,12,14,16]])
arr2 = np.array([[1,3,5,7],[9,11,13,15]])
concart = np.concatenate((arr1,arr2), axis=1) # 1=rows and 0=columns
print(concart)

In [74]:
# Unique Occurence

arr_u = np.array([1,2,3,4,2,3,4,5,6,7,8,9,8,6,5,44,55,3,4,5,66,])

arr_uniq = np.unique(arr_u)
print(arr_uniq)

index = np.unique(arr_u, return_index=5)
inverse = np.unique(arr_u, return_inverse=True)
x,y = np.unique(arr_u, return_counts=True)
print(index)
print(inverse)
print(x)
print(y)

[ 1  2  3  4  5  6  7  8  9 44 55 66]
[ 1  2  3  4  5  6  7  8  9 44 55 66]
[1 2 3 3 3 2 1 2 1 1 1 1]
