In [ ]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd 

In [ ]:
# Creating a dataset ftom data frame
# Features or independent variables are those used in predicting results
# Dependent variable is the result of the prediction in the last column
# iloc is used in locating indexes. The range includes the lower bound and excludes the upper bound

dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values # : means the range and -1 means less the last column
y = dataset.iloc[:,-1].values
print(dataset)
# print(x)
# print(y)

In [4]:
# Handling missing data
# We can replace missing values with the mean, median or most used variable
# Transform returns the columns with the replacement done. To update the replacement, we assign transform to x 

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan,strategy='mean') # replace all missing values represented by na with the mean
imputer.fit(x[:, 1:3]) # Fit expects only columns with numerical values
x[:, 1:3] = imputer.transform(x[:, 1:3]) # Returns the new updated version of x
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [6]:
# Encoding the independent variables
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough') # Pass through will not encode the other columns
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [7]:
# Encoding the dependent variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]
